/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "post.login": [],
    "dashboard": [],
    "user.index": [],
    "user.update": [],
    "items.index": [],
    "items.create": [],
    "items.store": [],
    "items.show": [
        {
            "name": "item",
            "required": true,
            "binding": "id"
        }
    ],
    "items.edit": [
        {
            "name": "item",
            "required": true,
            "binding": "id"
        }
    ],
    "items.update": [
        {
            "name": "item",
            "required": true,
            "binding": "id"
        }
    ],
    "items.destroy": [
        {
            "name": "item",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.index": [],
    "categories.create": [],
    "categories.store": [],
    "categories.show": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.edit": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "sales.report.pdf": [],
    "sales.report.excel": [],
    "sales.index": [],
    "sales.create": [],
    "sales.store": [],
    "sales.show": [
        {
            "name": "sale",
            "required": true,
            "binding": "id"
        }
    ],
    "sales.edit": [
        {
            "name": "sale",
            "required": true,
            "binding": "id"
        }
    ],
    "sales.update": [
        {
            "name": "sale",
            "required": true,
            "binding": "id"
        }
    ],
    "sales.destroy": [
        {
            "name": "sale",
            "required": true,
            "binding": "id"
        }
    ],
    "cashier.index": [],
    "cashier.store": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
